from pydantic import BaseModel
from datetime import datetime, timezone
from typing import Literal
from pydantic import BaseModel, Field
import uuid

class TraceBase(BaseModel):
    """
    The base class for all traces. This class is only meant for 
    inheriting shared fields for the other trace schema classes. 
    For typing purposes, the `Trace` union type should be used instead.
    """
    id: uuid.UUID = Field(default_factory=lambda: uuid.uuid4())
    timestamp: float = Field(default_factory=lambda: datetime.now(tz=timezone.utc).timestamp())


class AIMessageTrace(TraceBase):
    """
    Trace that logs a message generated by an AI agent.
    """
    kind: Literal["ai_message"] = "ai_message"
    agent_name: str
    content: str
    is_main_agent: bool = Field(default=False)


class HumanMessageTrace(TraceBase):
    """
    Trace that logs a message sent by a human user.
    """
    kind: Literal["human_message"] = "human_message"
    username: str
    content: str


class ToolTrace(TraceBase):
    """
    Trace that logs a tool call by an AI agent.
    """
    kind: Literal["tool"] = "tool"
    called_by: str
    name: str
    bound_arguments: dict
    return_value: str


class ImageCreationTrace(TraceBase):
    """
    Trace that logs the creation, contents, and caption of an image by a tool.
    """
    kind: Literal["image"] = "image"
    base64_encoded_image: str
    caption: str


Trace = AIMessageTrace | HumanMessageTrace | ToolTrace | ImageCreationTrace
"""
A union type representing all the traces that can be used for logging agent and user activity.
"""
